version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
          GOOGLE_API_KEY: ${GOOGLE_API_KEY}
          TAVILY_API_KEY: ${TAVILY_API_KEY}
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
